### ISSUE TITLE
Which cmake version should we use?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#123]
Why do we use version 2.6 of cmake? Why not a later version? Are there any useful features in later versions?

**Comment by crodnun** [comment]
I put this version just to be backwards compatible, doing a copy & paste from previous makefiles. Latest version available and installed depends on each distribution or operating system normally, official one is 3.8 but normally not everybody has thi one (I mean the package managers thet install this stuff). My policy here is to put an old one instead of checking the operating system, this way we are kind with everybody.

**Comment by tjayrush** [comment]
Good. Closed.
