### ISSUE TITLE
Turn on all warning no matter how minimal in all builds

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#173]

**Comment by crodnun** [comment]
Seems already done, this is done at CMAKE with the global variable CMAKE_CXX_FLAGS and adding to this the value "-Wall" to show every warning.
If you check the CMakeLists.txt files,  it seems present everywhere.
You can improve the same or be a pickier adding also the option -Werror and convert every warning into error to stop compilation when any warning is generated, just to pay attention on it and fix the root cause.

**Comment by tjayrush** [comment]
I added -Werror to all CMakefiles.txt files.

**Comment by tjayrush** [comment]
I tried adding -Wextra as well, but there were too many warnings (errors), so I stopped. Closing this for now.
