### ISSUE TITLE
Some of the shell scripts from ./src/tools/scripts don't work

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#175]
There are some scripts in ./src/tools/scripts which do various things. On Ubuntu, they are not 'executable' when they are first cloned. Can we change the CMakeLists.txt file to not only copy the files from this folder to ./bin but also make them executable.

Currently, on Ubuntu, I have to do this:

    cd ./quickBlocks/bin
    chmod uog+x colorEcho 

for example.

**Comment by crodnun** [comment]
These are bash scripts, discouraged at repository, they will only work on Linux/MAC environments but not portable to e.g. windows. We should convert them into python or perl to make them available for everybody.

Regardless the type of file, cmake has a directive to change permissions at installation:

install(
    FILES XXXXXXXXX
    PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
    DESTINATION YYYYYYYYYYYYYY
)

you can use it instead of using the copy one currently used

**Comment by crodnun** [comment]
I have done this, update the CMakeList.txt and pushed the change into repository (develop branch), do not forget to pull first and get it, it sets 750 permissions to these scripts

**Comment by tjayrush** [comment]
It works. We can worry about this later. I will write a bug against the tools project to switch these to python. Most of these scripts are for my convenience and will probably be removed at some point.

Create #180
