### ISSUE TITLE
Running cmake in the ./src folder

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#197]
Twice I've made the mistake of running 'cmake ../src' from the ./src folder. This, of course, creates hundreds of files and folders in the ./src folder that I have to then remove as they should have been created in the ./build folder.

Is there any way to tell cmake to ***only*** build in the ./build folder?

**Comment by crodnun** [comment]
By design, there is not a way to specify that in CMakeLists.txt. It is designed for the user to be able to build the project in whatever directory they want. One idea that comes to my mind is to add a checking at the root CMakeLists.txt file to check that current working directory, where we are running the cmake command matches a regular expression or similar and has "A/B/C/build" format.
Let me know if this could work for you and I will implement the solution.

**Comment by tjayrush** [comment]
I think we can just ignore this problem. The more often it happens, the more it will train my brain to stop doing that since it takes a long time to clean up. The punishment will help me learn. I am going to close this.
