### ISSUE TITLE
Doubts regarding ethName usage

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#202]
ethName [-a|-c|-e|-l|-m|-s|-v|-h] term [name]  
Purpose:  Find a name given an Ethereum address, or find an address given a name.

It is clear that we can search by address or by name, but it is not clear if we can use it this way:

ethName [options] term   ----- To search by address
ethName [options] name  ----- To search by name

If this is the usage, maybe the help command should be a logic OR:

ethName [-a|-c|-e|-l|-m|-s|-v|-h] term | name  

term OR name must be passed as parameter always. Right now looks like name is optional and term must be present always.

Let me know if this assumption is correct, otherwise what  would be the correct usage, as a user I have doubts, looking at your test cases seems that we can use one or both, but the purpose message says (one or the other)

**Comment by tjayrush** [comment]
If the user provides one search term, it will match if either name or address matches.
If user provides two terms, it will match if the first matches an address and the second matches a name (in the same record). In other words, both must match.

Something like this, but I don't know how to write it correctly:

    ethName [.....] address or name (if one term is given)
    ethName [.....] address and name (if two terms are given)

As I was trying to say yesterday, we could also change the interface. Maybe something like this:

    ethName -a address -n name ....

and then rework the remainder of the less important parameters (for example use -t or --terse to export address only instead of -a).

In general, we want to make all the commands in "as expected" a way as we can. So a regular, every-day Linux user would find what makes the most sense.

This (making it make sense) is probably one of the most important things you can help me with.

**Comment by crodnun** [comment]
And what about being order independent at this command? I mean to do both searchs using name & address  and if no match if found do the opposite (address  & name) this way, user does not have to remember the order, just pass keys to the search, 1 or 2.

This way you could have a help like this:

ethName [-a|-c|-e|-l|-m|-s|-v|-h] keys-list
where keys-list can contain a name, an address or both (space separated list)

Just brainstorming

**Comment by tjayrush** [comment]
Maybe I could even look at the input. The address, if it's well formed, will be hexidecimal and most likely start with '0x' (although they should be able to look for parts of an address such as the last four digits which a lot of people remember).

Maybe this:
       if the term has '0x' then search address first then name
       if the term does not have '0x' then search name first then address

in this way we could also allow any number of terms and do an 'and' or an 'or' option.

**Comment by crodnun** [comment]
If you do format checkings, you will lose the search power I think. A new test for the list, search without 0x at the address. ;-)

**Comment by tjayrush** [comment]
I like your comment above regarding 'keys-list' very much.  If you can articulate it, please suggest how you think this would work.

**Comment by crodnun** [comment]
Something like this, could work:

ethName [-a|-c|-e|-l|-m|-s|-v|-h] keys-list
where keys-list is the list of keys we want to use in our search. We can use one or multiple of the following keys:

addr name source

Search results will return those entries matching all the search keys passed to the command.

**Comment by tjayrush** [comment]
Please close this issue for now. I will re-open it once we're done with the 0.2.0 release. It's noted in #293.

**Comment by crodnun** [comment]
Will be fixed in next milestone
