### ISSUE TITLE
Logging in to remote Ubuntu and doing 'git push'

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#231]
On my Mac, when I do git push, it simply loads the changes. On Ubuntu, when I do the same, it asks me to login to github. How can we make it work without login

Also--when I open command shell on quickblocks.io it does not require a login, when I do that to the new Ubuntu, I must log in.

**Comment by crodnun** [comment]
Hi Thomas, this is related with how you did the initial setup of the repository (when you created it at github). Did you supply any ssh key there? That probably is configured/present at your MAC but not at your Linux server.
When you have the ssh keys properly configured no need to do login but when they are missing you has to do the login/password step. 
Maybe you could add also mine at github repository (I suffer the same issue every day, and have to enter my user & password at every push :-(). 
Every server you want to work with, should have the ssh keys configured at github properly configured (remember the private part, the public is configured at github). 

I see here two enhancements required:

1) Add a public key for me at github (I can supply it)
2) Help you to configure those servers where the key is not installed and connected with github (at my side everywhere).

Look at this pointer:

https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by tjayrush** [comment]
Please supply your ssh public key and I will add it to git-hub repo. I found the location under settings where I can add public keys.

I tried to do my part by creating a new public/private key pair at my Ubuntu box. When I did ssh-keygen two new files appeared in ~/.ssh (one id_rsa.pub and one id_rsa). I copy and pasted the contents of the id_rsa.pub file into the github settings. Of course--like everything else for me--it didn't work. Any thoughts?

**Comment by crodnun** [comment]
OK Thomas, is not your fault. You need then an extra step to add the private key locally at your Ubuntu box. No worries.

Follow the instructions that github provides here:

https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

And let me know if it works, if you want you can add my public key too meanwhile, find it attached at this post.
[Identity .txt](https://github.com/Great-Hill-Corporation/quickBlocks/files/1233416/Identity.txt)

**Comment by tjayrush** [comment]
I think the private key is at the Ubuntu box.  I created it, on the Ubuntu box with ssh-keygen, and here's a listing of the ~/.ssh folder. I did not do the second part (ssh agent) because it appeared to be instructions for the Mac.

root@ubuntu-2gb-nyc3-01:~/quickBlocks/build# ls -l ~/.ssh
total 12
-rw------- 1 root root 1232 Aug  9 13:49 authorized_keys
-rw------- 1 root root 3326 Aug 17 15:07 id_rsa
-rw-r--r-- 1 root root  745 Aug 17 15:07 id_rsa.pub

I added your public key to the repo. Let me know if that worked.

**Comment by tjayrush** [comment]
I'm sorry. I tried to find the place to store your public key, but I can't find it. Where do I do that on github?

**Comment by crodnun** [comment]
Hi Thomas, here you have the instructions they provide to do the same:

https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

Let me know if further help is required.

**Comment by tjayrush** [comment]
I'm confused. I don't think I want to add your public key to my github profile do I? I added status-discuss to this one, we can talk about it on Monday at 9:00 am my time.

**Comment by crodnun** [comment]
Hi Thomas, I have studied this issue and I found the root cause of this. We are not using ssh as protocol to push the files, so can not use our ssh key for this, if you look at the URL when you execute the "clone" command, we use https://xxxxxxxxxxxx, git supports both: https and ssh but we are currently using https.

So if we keep using https, no longer required to use ssh keys, you can delete mine if you want to.

Doing a quick research I found a better solution: use the password cache (you only need to enter it once and then forget till next time when cache value expires)

Steps required are the following:

1) Execute this command to enable the password cache:

>    git config --global credential.helper cache

2) Define the password expiration time, I set it to 100 years (unfortunately I will not be here to check if it expires or not in 100 years, lol):

> git config --global credential.helper "cache --timeout=86400000"

3) Then do push and enter the password again, this will be the last time you will need to do this till cache value expires.

After this step, every push will not request you a password anymore. Test it and let me know how it works at your side, I did it at my Ubuntu only.

**Comment by tjayrush** [comment]
Closed in lieu of #262 until 0.2.0 is released
