### ISSUE TITLE
make readme is broken

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#239]
I did something to the `make readme` command and it is now not working.

Can you please fix this for me? You only have to fix it in one place (say ethName) and I will propagate the fix to the rest of the tools and apps.

**Comment by crodnun** [comment]
Should be fixed now, double check the same at your side.

The fix required is the following:

At root CMakeLists.txt file we define the function:

--------------------------------------------------------------------------------------------------------
function(build_readme sourcePath toolName)
    set(README_FILE "${sourcePath}/README.md")
    set(TOOL_README_TEMPLATE "${sourcePath}/docs/README.tmpl.md")
    add_custom_command(OUTPUT help.txt COMMAND ${toolName} "-th" ">" help.txt "2>&1")
    add_custom_target(readme COMMAND "${TAG_REPLACE}" "${TOOL_README_TEMPLATE}" "${toolName}" help.txt "${README_FILE}")
endfunction(build_readme)

-----------------------------------------------------------------------------------------------------------

Here we have a custom command to  generate the help.txt and a custom target that can be invoked doing "make readme".

The key here is that the custom target depends on the "help.txt" file that must be generated first, executing the custom_command.

To do this you need to add at DEPENDS parameter at add_custom_target() statement, to say, I need this file present first (invoke the suitable command to generate it).

The line fixed now (and pushed to repository) looks now like this:

add_custom_target(readme COMMAND "${TAG_REPLACE}" "${TOOL_README_TEMPLATE}" "${toolName}" help.txt "${README_FILE}" DEPENDS help.txt)

with 

add_custom_command() you define your own commands, but they are not executed if not needed, to execute them you need to use the DEPENDS param.

**Comment by tjayrush** [comment]
This now does not fail (as it did before), but neither does it build the readme file. I changed a the text output for the help text for "Other Options" (you can see what the new text should look like here: https://github.com/Great-Hill-Corporation/quickBlocks/tree/develop/src/apps/ethprice).

When I do this:

    cd build
    rm -fR *
    cmake ../src
    make (it builds with no errors)
    make readme

I would expect all the README.md files in all the folders to get rebuilt, but they do not seem to be changing. In fact, oddly, it changes the ethprice README.md file back to the previous version even the help files in ./tests/gold/apps/ethprice/ethprice_README.txt is updated.

Something is definitely not working properly.

**Comment by crodnun** [comment]
OK Thomas, let's review it together. I only worked on ethName as you requested, and I can see that each time I run the "make readme" it generates again the README.md file for this tool. 

We can review this together in our next meeting, because to do it recursively, you need to add the target everywhere and maybe there is any intermediate directory where you forgot to add it.

If you run for example the "make readme" at tools level:

$ pwd
/home/quickblocks/quickBlocks/build/tools

tools$ make readme
make: *** No rule to make target 'readme'.  Stop.

At apps level:

apps$ make readme
make: *** No rule to make target 'readme'.  Stop.

So seems that the recursive readme is not in place, only the individual ones:

quickblocks@ubuntu-1gb-lon1-01:~/quickBlocks/build/apps/ethprice$ make readme
[ 26%] Built target wallet
[ 51%] Built target util
[ 55%] Built target abi
[ 75%] Built target ether
[ 82%] Built target acct
[ 93%] Built target token
[ 97%] Built target ethprice
Scanning dependencies of target readme
[100%] Generating help.txt
Wrote file /home/quickblocks/quickBlocks/src/apps/ethprice/README.md
[100%] Built target readme

**Comment by tjayrush** [comment]
I had a .gitignore in ./src/apps/ethslurp that listed docs as an exclusion. Should be fixed.

**Comment by crodnun** [comment]
OK, now the "make readme" commands executes correctly from root level.

If I run it at build directory, I am able to generate the following new files that github says that have been modified:

modified:   src/apps/ethprice/README.md
        modified:   src/apps/ethslurp/README.md
        modified:   src/apps/grabABI/README.md
        modified:   src/apps/makeClass/README.md
        modified:   src/test-libs/abilib/abiTest/README.md
        modified:   src/test-libs/acctlib/acctTree/README.md
        modified:   src/test-libs/etherlib/printFloat/README.md
        modified:   src/test-libs/etherlib/sha3/README.md
        modified:   src/test-libs/utillib/jsonTest/README.md
        modified:   src/test-libs/utillib/tomlTest/README.md
        modified:   src/tools/ethName/README.md
        modified:   src/tools/getBalance/README.md
        modified:   src/tools/getBlock/README.md
        modified:   src/tools/getBloom/README.md
        modified:   src/tools/getLogs/README.md
        modified:   src/tools/getTokenBal/README.md
        modified:   src/tools/getTrace/README.md
        modified:   src/tools/getTrans/README.md
        modified:   src/tools/isContract/README.md
        modified:   src/tools/whenBlock/README.md
        modified:   src/tools/whereBlock/README.md

Could you detail a bit more what is exactly the issue here, all these files are generated as new files at my side. Checking their format they seem to have the right format.

We need to clarify here what do you mean with "does not work". At issues reporting we should avoid to use these generic expressions and give more details of what is the error, the output obtained, the command executed, etc,... otherwise we can delay the fix a lot. I encourage you here to put the exact commands you run and what is wrong at your side.

At my side I did:

cmake ../src
make readme

And all the README.md files listed above are generated correctly.

**Comment by tjayrush** [comment]
Look at this file: https://github.com/Great-Hill-Corporation/quickBlocks/tree/develop/src/apps/ethprice

You can see two things. The 'purpose' ends with the words 'and other purposes.' and the Other Options section shows the options in a grey table.

Next. Go to your local repo and run 'make readme' from the ./build folder.  It appears to work, but do 'git status' and you will see that it only changed ./src/apps/ethprice/README.md, and that it changed it back to the 'old' style README.

What should happen is that ./src/apps/ethprice/README stays the same, and all other READMEs get the 'gray' Other Options table.

Maybe we do need to do a phone call if it's too confusing.

**Comment by tjayrush** [comment]
I have no idea what changed, but it's working now. I think it had to do with me doing a rm -fR * in ./build folder (that is, rebuilding everything). I then did

     cd ./quickBlocks/build
     rm -fR *
     cmake ../src
     make
     make readme
     make test

and the README.md files were changed. I will close this, and only open it if it stops working again.
