### ISSUE TITLE
Max number of transactions option at ethslurp seems not working

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#255]
When I run:

> ./ethslurp -m:10 0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC

I expected to dump only 10 transactions but seems to gather all them, at least as a user I obtain the same results that running it without the "-m" option

**Comment by tjayrush** [comment]
Nice find, but this wasn't intended to limit the number of records 'displayed.' It was intended to limit the number of records retrieved from etherscan that are not already in the cache. This is a 'safeguard' to ensure the tool doesn't appear to hang.

Since this is not really an appropriate user facing option, I made this a hidden command. It will still be accepted by the tool, but it won't be documented. I did add it to the list of hidden options here: #238 

You may close this.

**Comment by tjayrush** [comment]
Referencing #85

**Comment by crodnun** [comment]
OK checked and now hidden.
