### ISSUE TITLE
Learning: Infura API

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#276]
The remote API: https://infura.io/

**Comment by crodnun** [comment]
Hi Thomas, as you requested me, I dedicate some time to learn and R&D ;-).  I reviewed the remote API that infura uses and played around with it. 

Pushed to repository, quick instructions to use it, hope this is what you were looking for, let me know if you need something else regarding this issue. 

Location:

src/other/docs/infura_remote_api_setup.txt

Basically is to configure an API key and then use the standard JSON request.

**Comment by tjayrush** [comment]
This is great. This is pretty much exactly the same interface that I already use against the locally running Parity node. The only difference is that I use http://localhost:8545 instead of http://mainnet.infura.io.... My goal is that my code works like this for getBlock for example:

```
if (the block is in the QB cache)
    return that block
else if (there is a local node use)
    get the block from there and optionally cache it
else
    get the block from Infura and almost definitely cache it
```

This is actually very interesting to the people at Infura because it could potentially take a huge burden off of their systems.

**Comment by crodnun** [comment]
OK, let me know if further information is required from infura.io. Otherwise we can close this issue. Document with notes and steps required is present at repository now if we need a reference in the future.

**Comment by tjayrush** [comment]
We will need it later. Thanks for putting it together. Just for your information the exact same interface is available from testrpc, infura, mainnet nodes, testnet nodes, private chains, etc. So--ultimately--quickBlocks should work with everything.
