### ISSUE TITLE
Improvement at addresses management

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#281]
Testing ethslurp I realized that addresses are case sensitive, 

If we pass the lower case format, it works:

0x63c8c29af409bd31ec7ddeea58ff14f21e8980b0

If we pass it in upper case, it is rejected.

0X63C8C29AF409BD31EC7DDEEA58FF14F21E8980B0

A good improvement to the system (at every tool, app) could be to support both formats and internally treat them in lower case.

**Comment by tjayrush** [comment]
Referencing #60

**Comment by tjayrush** [comment]
I'm not sure how to handle this. The problem is not the address itself, but the 0X at the start of the string. Valid addresses must start with '0x' not '0X'. The same exact string with '0x' as the first two characters works (as it should). I think I will make a special case to test for '0X' and complain specifically about that as opposed to allowing '0X' which seems like a bad idea.

**Comment by tjayrush** [comment]
This may be closed. I added a better message when encountering an invalid address such as this one.

**Comment by crodnun** [comment]
Now working fine and supports upper case values 0x .....
