### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#309]
Notes:

`make install` works but does nothing

- The following directory structure should exist after the install

    |-- ${HOME}/.quickBlocks
        |
        |-- configs
        |-- slurps
        |-- abis
        |-- makeClass
        |-- grabABI
        |-- chifra

In the folder ${HOME}/.quickBlocks there should be a file called quickBlocks.toml with this structure:

	[version]
	current=0.2.0

	[settings]
	api_provider=EtherScan
	api_url=http://etherscan.io/apis
	api_key=<NOT_SET>
	block_data_path=<NOT_SET>

	[display]
	fmt_fieldList=
	fmt_txt_file=[{HEADER}]\n[{RECORDS}]
	fmt_txt_record=[{FIELDS}]\n
	fmt_txt_field=\t[{FIELD}]
	fmt_csv_file=[{HEADER}]\n[{RECORDS}]
	fmt_csv_record=[{FIELDS}]\n
	fmt_csv_field=["{FIELD}"],
	fmt_html_file=<table>\n[{HEADER}]\n[{RECORDS}]</table>\n
	fmt_html_record=\t<tr>\n[{FIELDS}]</tr>\n
	fmt_html_field=\t\t<td>[{FIELD}]</td>\n
	fmt_json_file=[{RECORDS}]\n
	fmt_json_record=\n        {\n[{FIELDS}]        },
	fmt_json_field="[{p:FIELD}]":"[{FIELD}]",
	fmt_custom_file=file:custom.txt
	fmt_custom_record=fmt_txt_record
	fmt_custom_field=fmt_txt_field

**Question:** Do we want to build .a files or .so files?

**Question:** Where should executables go? Where should .h files go? Where should .a files go?

**Question:** the install needs to install the library files and the .h files in the correct location so they can be found by the end user's code

**Question:** What about some sort of un-install option?

**Question:** Will the install directory be in the end user's path?

**Comment by crodnun** [comment]
OK Thomas, 

Let's go step by step. 

1) "make install" target

   Installation target is ready and pushed to develop branch.  
   When you type "make install" it creates the desired directories, assign permissions and creates the file quickblocks.toml.
  When files already exists, it warns user that it has been renamed.
  To install the quickblocks.toml file we need a template somewhere, I created it under src/other/install
  (Notice that install is also a new directory to put there future installation stuff)

2) Problems with quickblocks.toml

   At this file the following parameter:   

   cachePath=/Users/jrush/.quickBlocks/slurps/

   Depends on your user, so we should define it somehow that it is user independent, maybe using the replaceTag python script that we have or similar. I let you decide the same.


3) Questions.

--------------------------------------------------------------------
Question1: Do we want to build .a files or .so files?
--------------------------------------------------------------------
This is just up to you, for me as final user, I prefer when tools do not depend on .so and they were linked statically with the .a. This way you only need to provide the binaries themselves, no need to supply libs.

If you want to supply the libs to everybody then I prefer again if someone provides me the .a. Only have to install one thing: my binary linked against the .a.

If there is something that will evolve and you need to patch continously the library, the best choice is .so. This way you just need to patch the lib and binaries will be fixed.

--------------------------------------------------------------------
Question: Where should executables go? Where should .h files go? Where should .a files go?
--------------------------------------------------------------------

Here it is pending to decide the architecture you want to create for them (bin folder, include folder, lib etc and what they should contain).

If you look at other projects they usually provide this structure:

DESTINATION/bin
DESTINATION/lib
DESTINATION/include

cmake allows users to configure the installation path when they run cmake, it is done this way:

cmake ../src -DCMAKE_INSTALL_PREFIX=/path/where/i/want/to/install

-------------------------------------------------------------------------------------------------------------------
Question: the install needs to install the library files and the .h files in the correct location so they can be found by the end user's code
-------------------------------------------------------------------------------------------------------------------

As developer, once you decide where to install a product, you should take care of this (on your own) and update your PATH, LIBRARY_PATH or INCLUDE_PATH to work with the libraries and executables installed, I do not consider this part of the installation because every developer likes to work differently. The only thing they need to know is where they were installed but we can not do this for them and update the paths and modify how they work.

-------------------------------------------------------------------------------------------------------------------
Question: What about some sort of un-install option?
-------------------------------------------------------------------------------------------------------------------

cmake does not support this directly but we can play around and create our own target for this.

-------------------------------------------------------------------------------------------------------------------
Question: Will the install directory be in the end user's path?
-------------------------------------------------------------------------------------------------------------------

Users can define it using the aforementioned variable at cmake step CMAKE_INSTALL_PREFIX
cmake ../src -DCMAKE_INSTALL_PREFIX=/path/where/i/want/to/install

**Comment by tjayrush** [comment]
This is all perfect. I will test your work here, and if I find any particular issues, I will open a new issue. After I test your work, I will close this issue.

One point: the cacheDir = /User/jrush.... line can be removed from the install. This will get inserted on the first run of ethslurp automatically using the end user's home folder. I should have removed that line from my instructions (as I did above).

I'll get back to you on this one.

**Comment by tjayrush** [comment]
In the above you say:

> When file (quickblocks.toml) already exists, it warns user that it has been renamed.

I presume this is the 'standard' way to do it? If yes, then this is fine. If this is non-standard (and there is a standard way to do this if the installed file already exists), then we can discuss. 

After thinking about this for a minute, it seems to be an okay way to do it.

**Comment by tjayrush** [comment]
## Point 2:

**Question1: Do we want to build .a files or .so files?**

**Comment by tjayrush** [comment]
## Point 3:

**Question: Where should executables go? Where should .h files go? Where should .a files go?**

```
DESTINATION/bin
DESTINATION/lib
DESTINATION/include
```
I think DESTINATION should be '/usr/local' by default (but I will defer to you because I don't really know where it should go). What is standard, I would say.

**Comment by tjayrush** [comment]
## Point 4:

**Question: the install needs to install the library files and the .h files in the correct location so they can be found by the end user's code**

I understand that the install does not set the PATH, INCLUDE_PATH, etc. Leave it up to the end user as you suggest.

**Comment by tjayrush** [comment]
## Point 5:

**Question: What about some sort of un-install option?**

Ignore un-install.

**Comment by tjayrush** [comment]
## Point 6:

**Question: Will the install directory be in the end user's path?**

As you suggest, this is not our problem. Ignore.

**Comment by tjayrush** [comment]
## Install these items in DESTINATION/bin

```
// A README file
README.md

// python scripts
clearCacheEntry.py
ethscan.py
replaceTag.py
testCheck.py

// currently shell scripts, but once converted to python scripts will have .py file type
ethgoog
getCode

// Compiled excutables (notice the uppercase/lowercase issues)
ethName
ethprice (but call it ethPrice -- rename this either in the build or during the installation which ever is easier)
ethslurp (but call it ethSlurp -- rename this either in the build or during the installation which ever is easier)
getBalance
getBlock
getBloom
getLogs
getReceipt
getTokenBal
getTrace
getTrans
grabABI
isContract
makeClass
whenBlock
whereBlock
```

**Comment by tjayrush** [comment]
Install all header files found in ~/src/libs/include into DESTINATION/include

Install all .a files found in ~/.src/libs into DESTINATION/libs

**Comment by crodnun** [comment]
Initial version of installation stuff is ready to deploy everything under /usr/local/quickblocks (this path is configured at root CMakeLists.txt, feel free to modify it).

IMPORTANT: If we deploy under /usr/local/ by default we need to do it using "sudo" or root, because we are touching common files at the system.  We should take this into account at instructions.

We now deploy the following structure after "make install":

- /usr/local/quickblocks
      --------- bin/         (tools, apps and python scripts selected)
      --------- include/   (all headers)
      --------- libs/         (6 .a files)

Kindly verify that it works at your side, DO NOT FORGET to use "sudo" for the make install step.

**Comment by tjayrush** [comment]
I modified the install root to /usr/local/qblocks instead of /usr/local/quickblocks just to make the include line in people's code a bit shorter.

I also noticed that you were creating the QuickBlocks config folders in ~/.quickblocks whereas in my installation I have it at ~/.quickBlocks (different capitalization). I changed this, but it might require you to remove some folders.

I tried this install without being the super user. I got this error message:

> CMake Error at libs/cmake_install.cmake:31 (file):
>   file cannot create directory: /usr/local/qblocks/include.  Maybe need
>   administrative privileges.
> Call Stack (most recent call first):
>   cmake_install.cmake:136 (include)
> make: *** [install] Error 1
> 

I then tried `sudo make install` and it worked.

I have a few questions about the installation. Should I create separate issues, or post them here?

**Comment by crodnun** [comment]
Hi Thomas, let's keep a single issue for installation stuff (this one). 

Clearly after looking at the results of this first attempt, we can not rely on common directories to deploy quickBlocks (/usr/local).

If we need to deploy the cache directories at $HOME, my suggestion is to use the $HOME also to deploy the bin/include/libs directories. Running "make install" with "sudo" allows us to install under /usr/local (owned by root normally) but spoils the rest of the installation under $HOME/.quickBlocks (installing them also as root), so I think that is better to use the $HOME of current user to install everything.

Something like this:

$HOME/.quickBlocks/xxxxxx     (for configuration and cache related stuff)
$HOME/qblocks/bin
$HOME/qblocks/include
$HOME/qblocks/lib

cmake does not contain any feature to change permissions on the fly and we have 2 choices here:

1) To install everything at local user
2) To look for alternatives apart from make install to create the $HOME/.quickBlocks part  (maybe an extra step after installation, with a python script or similar to generate the cache hidden directory)

We have 2 installations, the qb SDK & tools and then the local user setup. We can not do both using the same user unless we deploy everything only for current user.

Let me know your feedback about the same, but clearly we can not mix installations with "root" user and "current" user, we have to solve this first, my favorite choice is to deploy everything under local user, no need to share it with other users at this stage, when the only thing they are doing is just tasting qb, no need to install it for all the users under /usr/local (as root user).

Cheers

**Comment by tjayrush** [comment]
Can we do the creation of ~/.quickBlocks and the installation of the files and folders under ~/.quickBlocks as part of the build? In this way, the installation of the SDK and binary could remain in /usr/local?

Something like this:
    make (which builds the product and creates ~/.quickBlocks if it doesn't exist, and does nothing if it does.
    make install (which only copies files)

In other words, include the creation of the ~/.quickBlocks folder in the build (but only if it does not already exist), and install the SDK otherwise.

I very much do not like the idea of installing in the user's $HOME folder. When any application installs files in my home folder, I totally do not like that. Our instructions can say something like "You may have to the following command using `sudo`.

I'd really like to find a solution that doesn't require installing files in the end user's $HOME. Or, if we have to, I would want the installer to give the user a change to change that folder at a prompt.

Your thoughts?

**Comment by crodnun** [comment]
OK, I will work on this path.

**Comment by crodnun** [comment]
Hi Thomas, let me know if this works for you.

I have integrated the generation of $HOME/.quickBlocks structure at build part as you requested.

When we type:

"make"

apart from compiling codes we now generate the structure of directories that every user will have under her/his $HOME.

The solution implemented is the following:

1) At root CMakeLists.txt I added a new target called "cache", feel free to rename it, if you have a better name for it.

It is the latest line at this file:

add_custom_target(cache ALL COMMAND ${CMAKE_COMMAND} -P ${CMAKE_SOURCE_DIR}/cache_setup.cmake)

As you can see it invokes a different cmake file present at same directory (new one).

I moved the directories generation stuff to a different file at same level: cache_setup.cmake

I did this to isolate the build part from the directories generation.

This new target is executed everytime we type "make"  (this is done with the ALL parameter).

You can generate it using 2 methods:

1) Every time you type "make" 
2) Executing the specific target itself  "make cache"  (Again feel free to rename it on your own)

This way after "make" we can do the SDK installation using "sudo" under /usr/local directory as we desired.

**Comment by tjayrush** [comment]
I think these three steps work as I would expect:

    cmake ../src
    make (creates local user stuff)
    sudo make install (deploys the SDK at the system and makes it available for every user)

but I have a few questions:

1. Can we move the build instructions in ~/cache.cmake into the ./src/other/install/CMakeLists.txt file and handle this in the regular way (with add_subdirectory in ./src/other/CMakeLists.txt). I'm not a big fan of any files in ./src other than subfolders and a README.md file.

2. The install of the ~/.quickBlocks creates a bunch of folders and then moves the existing config file if it exists, then copies in the new config file. This doesn't  work since it overwrites customizations of the config each time a user builds. This breaks my 'monitors.' [This line](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/cache_setup.cmake#L17) should say `if (NOT EXISTS...)` and then only copy the config file if there is not already there. I had to comment out this part from my local build so it wouldn't break my monitors (but I also made a change to my monitors to make them more robust in this case.)

**Comment by crodnun** [comment]
Perfect I will accomodate it to your needings

**Comment by tjayrush** [comment]
Please focus on this issue first and push your results as soon as you can.

**Comment by crodnun** [comment]
They are pushed now, check the same at your side. Changes added:

1) .toml file is not overwritten, only created if none is present
2) Moved the cache.cmake file to install directory as you requested.

Let me know your feedback about the same.

**Comment by tjayrush** [comment]
I made a few changes and pushed them back up. I tried these tests:

    // running with an existing ~/.quickBlocks folder
    cmake ../src
    make

it correctly does not overwrite existing configuration

Then I did this:

    rm -fR ~/.quickBlocks
    cmake ../src
    make

and it properly created the files and folders with the correct data...

The I did this:

    rm -fR ~/.quickBlocks
    cmake ../src
    make install (without sudo)

It properly created the folders in ~/.quickBlocks and the proper files, but it did not copy anything into /usr/local or /usr/local/qblocks (because it wasn't 'sudo'.

The I did this:

    rm -fR ~/.quickBlocks
    cmake ../src
    make
    sudo make install

And this works as expected (created ~/.quickBlocks with correct permissions, copied files into /usr/local/qblocks). Finally, I did this (which is what I originally did):

    rm -fR ~/.quickBlocks
    cmake ../src
    sudo make install

Unfortunately, this is still gives the ~/.quickBlocks and all files and folder under it ownership by 'root'.

**Question for you:** do we care? I think a user who does 'sudo make install' might know what the problem is and simply correct it with 'sudo chown -r <user>:<group> ~/.quickBlocks. Do we really need to fix this if they don't follow our instructions (which will tell them to do `make` before `make install`.

**Comment by crodnun** [comment]
Hi Thomas, the last sequence you put here (that generates the root directories) I think that is unavoidable. 

Now we do 2 types of setup:

1) With "make" we install local user directories
2) With "sudo make install" we install the SDK (under /usr/local/qblocks by default)

When we run only "make install" directly, skipping the "make" step, we are doing everything as root (because make install, depends on make)
I think that forcing them to use the right steps will skip this issue as you mentioned. Otherwise we will have to rethink it a bit more because to "install" all the binaries must be available first (make is run to ensure this).

The key is always at the same point, we want to install 2 things, using 2 different users and for this we need to use 2 different commands, if we skip the "make" as local user we can not install it locally, if we run the SDK part as local user we do not have permissions.

I will investigate it a bit more, but I think that user should only run "make install" after "make"

**Comment by tjayrush** [comment]
Okay. I think this will be in the instructions (doing make, then make install). If someone runs make install without first running make and then wonders why the ~/.quickBlocks is owned by 'root' they can send me an email. Let's close this one. It works as i think it should in the normal case.

Since I opened this one, I am going to close it. (This one is getting too long to read anyway).

I opened two new issues to track the progress of the install: #355 and #356
