### ISSUE TITLE
whenBlock modes clearly identified

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#325]
As we did with other commands, we need to clarify in the help that we can work in 2 modes with this tool:

1) Search mode

2) List mode

This is just an improvement at help message.

**Comment by tjayrush** [comment]
Can you please suggest a wording change? I sort of understand what you mean, but not really. You're better at making the list of options [with [all its dashes] and (options)] <mode>. I don't know how to write those.

**Comment by crodnun** [comment]
What about these three modes at command line:

./whenBlock [-a] [-v]  date/block | -l | -h

1) [-a] [-v]  date/block    --- Search by date or block with additional options
2) -l  ----------- List mode
3) -h  ----------  Help mode

**Comment by tjayrush** [comment]
This is perfect, but it brings up the issue that, technically, --help works this way in every tool.

Since I don't want to get diverted right now, I'd like you to close this. I've referenced it in #293 which helps me keep track of delayed issues. We will revisit this (or a much larger issue called "correct format for all usage lines in help files") at a later date.

**Comment by crodnun** [comment]
OK, closing per Thomas request

**Comment by tjayrush** [comment]
We can revisit this when we move to rust where we will be using a much better command line parser.
