### ISSUE TITLE
The --verbose option everywhere accepts any value

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#327]
I detected this at whenBlock but probably is a general issue.

If we run:

./whenBlock -v:whatever    

It executes correctly.

Does it do anything? The level can be any arbitrary string, not checked that it is an integer. It is really used somewhere?

**Comment by tjayrush** [comment]
I fixed the fact that it will accept any values, but you are correct that in many cases it has no use. Many tools have only a single value ('on' or 'off'), some have no effect with --verbose, some use the verbose level. I am not going to fix bugs related to --verbose, so please go ahead and close this, since it's about accepting invalid input. I documented the --verbose issue here #338 (which is now closed, but I will re-open it after 0.2.0).

**Comment by crodnun** [comment]
Reviewed, closing
