### ISSUE TITLE
isContract treats un-existing addresses the same way than non-contract addresses 

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#334]
If we run the command with any (made-up) address, valid format but it does not exist:

./isContract 0x000001f568875f378bf6d170b790967fe429c810

isContract argc: 2 [1:0x000001f568875f378bf6d170b790967fe429c810] 
isContract 0x000001f568875f378bf6d170b790967fe429c810 
isContract(0x000001f568875f378bf6d170b790967fe429c810): false

We report it as non-contract address, but it does not exist, if possible we should distinguish those addresses that really do not exist from those that can give us a result.

Attached screenshot of ethscan.io that demonstrates that it does not exist.

![image](https://user-images.githubusercontent.com/16229970/29957671-fd702c5e-8eee-11e7-921a-9c28232032cf.png)

**Comment by tjayrush** [comment]
You've hit upon quickBlocks' distinguishing characteristic. You'll notice that EtherScan does not say that the account does not exist--every 40 character (20 bytes) hexadecimal number is a valid Ethereum account, and in that sense, they all exist.

Etherscan indexes transactions at every block and can filter per account. I could do this with quickBlocks, but if I did, I would almost certainly need very much more powerful computers than I current use: that is, a Mac laptop.

The first most important goal of quickBlocks is speed and accuracy. The second most important is an absolute minimal impact on the machine (in both CPU usage and especially hard disk space). The next most important is to stay fully decentralized (i.e. behind the Ethereum node).

There's a whole part of quickBlocks (the private part) that you've never seen called 'monitors.' Monitors build per-account lists of transactions. (What would be needed to report "No transactions".)

Because I want to maintain a minimal impact on the machine, I cannot do a per-block indexing of transactions per address. First, it would do a huge amount of calculations that don't need to happen, and secondly it would take up major disc space. QuickBlocks only builds lists of transactions per account when the end user asks us to, and this is done through the 'monitor' (private) code. 

There are many people who have built clones or copies of Etherscan--every one of them on powerful machines centralized behind a web interface and held by a third party. QuickBlocks is the only project that I know of (or anyone else knows of) that provies per-account lists of transactions in a fully decentralized way. This is why people are interested in what I'm doing.

So--after that long winded explanation--please close this issue as a non-issue. It's a great point, but it doesn't apply to this tool.

**Comment by crodnun** [comment]
OK understood
