### ISSUE TITLE
Testing for three-level cache when searching for Ethereum data

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#340]
Using the command `getBlock 1001001` only as an example (this would apply to all tools), the system should work like this:

```
if (the block is found in the quickBlocks cache)
    return the block to the user
else if (the there is a locally running node)
    retrieve the block from the node
    store the block in quickBlocks' cache
    return the block to the user
else if (a fallback server is configured -- i.e. infura)
    retrieve the block from the node
    store the block in quickBlocks' cache
    return the block to the user
```

What this means is that, if a fallback node is configured (I'm debating if it should be configured by default), then the test cases should all work identically no matter where the data is being pulled from.

To test this we want to run the test cases with:

1. **No local node running and no configured fallback and no cache**
    -- Should fail with a good message
    -- What happens when the ~/.quickBlocks folder does not exist?
    -- Does the ~/.quickBlocks folder get created?
2. **Local node >> not << running with a configured fallback and no cache (possible default)**
    -- The first time it runs is will be slow
    -- The ./quickBlocks folder and the cache should be created
    -- The second time it runs it should be significantly faster
3. **Without removing the cache, run with a local node running**
    -- No change in data or speed
    -- Some test cases may speed up because no round trip to a remote (overloaded) server.
4. **Remove the cache, leave the local node running**
    -- No change in data
    -- First run slower, second run faster
    -- Cache should be re-created

At this point, we have a locally running node and a local quickBlocks cache. This is the fastest mode and the optimal configuration. Now we

5. **Turn off the locally running node**
    -- Should work without fail -- same data
    -- Should pick up the data quickly from the cache
    -- Some tests, that hit the node such as isContract, may be slower
6. **Remove cache (and disable it so it doesn't get re-created)**
    -- Should run fine from the fallback node

I'm not sure how this would be tested, and I don't think we have to test it continually (that is we don't have to automate this testing).

**Comment by crodnun** [comment]
Hi Thomas, let's go step by step. I put here the results of my tests once done, then you review its behaviour, do any fix if required and we can go ahead with other scenarios.

Today I tested the following scenarios:

**No local node running and no configured fallback and no cache**

-- Should fail with a good message

**********************************************************************************

Yes, it is displayed the following message:

carlos@ubuntu16:~/projects/quickBlocks/bin$ ./getBlock 1001001 

	Warning: The request to the Ethereum node resulted in
	following error message: Couldn't connect to server.
	It is impossible for QuickBlocks to proceed. Quitting...


**********************************************************************************


-- What happens when the ~/.quickBlocks folder does not exist?


**********************************************************************************

Nothing happens, the Warning message is displayed and the following structure is created

~/.quickBlocks
~/.quickBlocks/cache


If you run it a second time, the same Warning is displayed but this time the file quickBlocks.toml appears under ~/.quickBlocks with the following content:

[settings]
blockCachePath=/home/carlos/.quickBlocks/cache/



**********************************************************************************

-- Does the ~/.quickBlocks folder get created?

**********************************************************************************

Yes

~/.quickBlocks
~/.quickBlocks/cache

directories are created the first time and the second time the quickBlocks.toml with the content described

**********************************************************************************

**Comment by crodnun** [comment]
Also tested this scenario.

**Local node >> not << running with a configured fallback and no cache (possible default)**
-- The first time it runs is will be slow    

It takes around 1,4 seconds to retrieve the information from infura fallback


-- The ./quickBlocks folder and the cache should be created

Again the same behaviour, the first time, only folders created, the second time the toml file

-- The second time it runs it should be significantly faster

No changes at speed detected, seems not using the cache, at least no cache stuff is generated in .quickBlocks folders

**Comment by crodnun** [comment]
Let's review these 2 scenarios and if they are OK, I will test the following ones and their combinations.

**Comment by tjayrush** [comment]
Please see my notes above under **NOTES TO CARLOS**

**Comment by crodnun** [comment]
OK, let's wait till we solve this part before testing more combinations. Let me know when we can proceed with the rest of scenarios after reviewing #354

**Comment by tjayrush** [comment]
Proceed with this as works. I explained a few things in #354.

**Comment by crodnun** [comment]
Hi Thomas, I moved forward with this issue, but when possible I need some clarifications about  what you exactly mean with "remove the cache" or "disable it to not get re-created" to run the tests correctly. I do not know yet how you organize the information at cache for a block, an address, etc,.. what are the files involved, and what we can remove and what not. 

What I did before is just to remove completely the .quickBlocks directory but after latest discussions, seems not correct and generates unexpected behaviour.

**Comment by tjayrush** [comment]
You can remove ~/.quickBlocks/cache folder which will delete the block cache. It should get re-created. Maybe this is getting too complicated. Do you want me to re-create separate issues for each scenario? Would that help?

**Comment by crodnun** [comment]
No worries, I will do my best with current information and let you know how it goes.

**Comment by crodnun** [comment]
I could not complete these tests (my parity issues after power shortage spoilt everything). I will try to address the same these days, not sure when but this task is not completed yet.

**Comment by tjayrush** [comment]
Sorry. Just re-assigning to you, so it doesn't appear in my list of things to do. If you wish me to delay it until 0.5.0, please just let me know and I will close it and then re-open it later.

**Comment by crodnun** [comment]
Yes, I will take care of it tomorrow (once I have enough blocks synced at Ethereum node after the disaster). If you want to freeze a version, feel free to close and postpone it

**Comment by tjayrush** [comment]
Even the --warp stalls between 2,400,000 and the end of the `stateclear`. Delaying in lieu of #293. Will re-open after 0.2.0.

**Comment by tjayrush** [comment]
I am going to say that, for the most part, this works exactly as described above in the original post. Closing.
