### ISSUE TITLE
Merge current develop branch with master one

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#360]
Hi Thomas, I do not know if you did this frequently this, but at some point before releasing the codes to the users. We need to merge contents and tag the master branch. People normally downloads the master branch with an specific tag.

**Comment by tjayrush** [comment]
I thought I would do this when I complete 0.2.0 issues, but I'm happy to do it now since the develop is so much ahead of the master. Should I merge it now? I think the first time I label it as a release will be when I finish the 0.2.0 issues. Please advise.

**Comment by crodnun** [comment]
No worries, we should merge periodically and tag only when release ready.

**Comment by tjayrush** [comment]
I decided to go ahead and merge this. It went smoothly (I think). I can now log in to my Ubuntu box, remove all remnants of quickBlocks, clone master and build all the tests. (The only failures are the ones we know about -- and the ones I will label as 'special' as per #351.

As we discussed previously, every Friday morning (or afternoon), you can post all your work and submit any issues you've been holding off on. I will then take the weekend to catch up on everything, and part of that can be to merge with master. I like the idea of trying to keep master up to date, especially since develop is getting progressively better and I'm not really changing any interfaces (in the libraries). Not to mention that I don't think anyone is using it (although we're getting more and more 'stars').

You may close this if you like.

**Comment by crodnun** [comment]
OK Thomas, it is a nice moment to review again all the systems supported so far and repeat the tests at every platform we claim is supported. I will do it these days

**Comment by tjayrush** [comment]
Okay. Please proceed. I think we talked about seeing what happens when you try to build on Windows. Do you want to do that as well?

**Comment by crodnun** [comment]
OK, tested it everywhere and only presents issues at FreeBSD (I open a different issue for the same to let you decide). If we do not support FreeBSD we can just unlink the help and remove it from the supported platforms list. 

Added instructions to build QB under MAC. I am not sure if they are accurate because I can not test them from scratch at my MAC (I think that had everything installed, so we will need a fresh MAC to confirm them).

Also tested under Windows and here the issue is that CURL needs to be downloaded, compiled, etc. Python installation is easy but CURL is a pain. We stop at the very first step when doing "cmake ../src" because CURL is a mandatory dependency. Here we have 2 choices, to let the users to find and build themselves CURL under Windows or to provide them the libraries already compiled to help them with this. I did a quick research but it seems not simple to do this, you have to use MINGW or similar environments to obtain the .a and .h that are always available under Linux/MAC with a simple command.

**Comment by tjayrush** [comment]
I'm glad this effort allowed you to find the error with missing trailing '/'.  That's good.

For the Windows build, I think we will put this on the back burner. We have this issue to track it: #249 

You may close this, I think, unless there's a reason not to.

**Comment by crodnun** [comment]
OK, closing now
