### ISSUE TITLE
Issue with parity

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#369]
Hi Thomas,

Yesterday we suffered a power shortage and unfortunately my parity terminal was closed abruptely at home.

Now I am not able to launch it again, it always errors out with this message:

Client service error: Client(Database("Invalid argument: You have to open all column families. Column families not opened: col7, col6, col5, col4, col3, col2, col1, col0"))

Doing some research, they say that the DB is corrupted and I need to delete the blockchain and start again :-( :-(. Did you face this issue before? It will be a pain if I have to resync everything, any advice is welcome... really frustrating to redo this again, clearly it is not safe to run it in a terminal, alternatives (maybe in background?)

Really pissed off with the bad news.... if we confirm that we need to restart again ...lol

**Comment by tjayrush** [comment]
Yikes!  I've been running Parity since about June of 2016 with no problems. I wonder if you ran out of disc space/

Before running Parity, I used to run a different Ethereum node called 'Geth.' That was a million times worse.

I think you're probably out of luck. I think your database is hosed. We might be able to use this as an opportunity though...read on...

We've been running Parity as a "trace enabled archive node" which places the heaviest burden on the node. It's the "worst" way to run it, in the sense that it takes forever to sync and creates a **_very, very large_** amount of data.

There's another way to run parity--the way almost every "regular" user runs it called --warp mode. "Warp" mode take much less time to sync and creates significantly less data, but it does not store anywhere near as much data as QuickBlocks needs (I think!)

I never ran QuickBlocks against a --warp synced node.

Maybe we can use this unfortunate situation to see what QuickBlocks does with a --warp node.  We may learn that it's not as bad as I think it will be (I image none of the data I need for blocks older than a few months will be available).

So--it might be a total waste of time--but it might be the best thing to happen for QuickBlocks. If we can provide "trace enabled archive node" data to end users who are running a --warp node -- that would really be something.

**Upshot:** Let's chalk this up to experience and run Parity with this command: parity --warp.  And then let it sync and see what happens when we run the test cases.

Does that make sense?

**Note:** you will have to "clean up" the corrupted database. Geth has a --removedb option to clean up the database, but I'm not sure Parity does. I think cleaning up the database is as simple as removing the parity installation. On Mac, it's at ~/Library/Application\ Support/io.parity.ethereum. Not sure where it is on Linux. IF YOU HAVE PRIVATE KEYS STORED ON THE NODE DON'T DELETE THEM. THEY ARE STORED IN THE SAME PLACE AS THE DATABASE!

**Comment by crodnun** [comment]
OK Thomas,

After doing some research I found the command to delete the DB and start again:

> parity db kill

I run it:

carlos@ubuntu-4gb-fra1-01:~$ parity db kill
2017-09-08 19:39:36 UTC Database deleted.

Running parity with the --warp option you mentioned we are blind :-(. It looks this way:

carlos@ubuntu-4gb-fra1-01:~$ parity --warp
carlos@ubuntu-4gb-fra1-01:~$ parity --warp
2017-09-08 19:41:51 UTC Starting Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0
2017-09-08 19:41:51 UTC Keys path /home/carlos/.local/share/io.parity.ethereum/keys/Foundation
2017-09-08 19:41:51 UTC DB path /home/carlos/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2017-09-08 19:41:51 UTC Path to dapps /home/carlos/.local/share/io.parity.ethereum/dapps
2017-09-08 19:41:51 UTC State DB configuration: archive +Trace
2017-09-08 19:41:51 UTC Operating mode: active
2017-09-08 19:41:51 UTC Configured for Foundation using Ethash engine



2017-09-08 19:44:19 UTC Removed existing file '/home/carlos/.local/share/io.parity.ethereum/jsonrpc.ipc'.
2017-09-08 19:44:24 UTC Public node URL: enode://2225f21623429dc187c8d1ca2754a992c16ccddc1ba1bd066247fbb3d259d59de461a97a7057876a04d52f0c779d46e7625c8f379cdabb67d365cda3b2e67387@46.101.238.80:30303
2017-09-08 19:44:49 UTC    0/25 peers   8 KiB chain 0 bytes db 0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-08 19:44:54 UTC Syncing       #0 d4e5â€¦8fa3     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #0    1/25 peers   8 KiB chain 0 bytes db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-08 19:44:59 UTC Syncing       #1 af43â€¦1154     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #1    1/25 peers   8 KiB chain 304 bytes db 0 bytes queue 18 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-08 19:45:04 UTC Syncing       #1 af43â€¦1154     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #1    2/25 peers   8 KiB chain 304 bytes db 0 bytes queue 19 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-08 19:45:09 UTC Syncing       #1 af43â€¦1154     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #0    4/25 peers   8 KiB chain 304 bytes db 0 bytes queue 19 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-08 19:45:13 UTC Reorg to #2 b495â€¦98c9 (af43â€¦1154 #0 d4e5â€¦8fa3 88e9â€¦6cb6)
2017-09-08 19:45:14 UTC Syncing       #2 b495â€¦98c9     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #2    3/25 peers   10 KiB chain 304 bytes db 0 bytes queue 152 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-08 19:45:19 UTC Syncing     #254 47e6â€¦0bb6    50 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed      #254    4/25 peers   272 KiB chain 9 KiB db 0 bytes queue 95 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
...
...

Let's see what happens, I will keep you posted here with the progress, speed, etc

**Comment by tjayrush** [comment]
Do this:

    cd build
    make
    cd tools/getBlock
    make test

and show me the results. Then do this for a few of the failed tests:

    diff ..../working/tools/getBlock/getBlock<test_name>.txt  ..../gold/tools/getBlock/getBlock<test_name>.txt 

so I can maybe see what happened.  Or just run the test directly from the command line of the ones that fail and maybe the ones that pass.

All of this is just informational, so don't worry too much about it. It's just interesting.

Now--I'm just thinking out loud--I wonder if we could configure it to ask the --warp node (which is way faster and stores significantly less data) and then fallback to the Infura node. I never really thought about this before, but that might be extremely interesting.

It's not **decentralized** but it's a pretty interesting idea.

**Comment by crodnun** [comment]
Here you have the results running "make test" again the parity --warp  node I have now (after the disaster, lol):


77% tests passed, 114 tests failed out of 499

Total Test time (real) = 664.54 sec

The following tests FAILED:
         88 - ethprice_at_00 (Failed)
         96 - ethprice_verbose_00 (Failed)
         97 - ethprice_verbose_01 (Failed)
        105 - ethslurp_not_found_address (Failed)
        106 - ethslurp_no_record_in_block_range (Failed)
        107 - ethslurp_single_block_range (Failed)
        108 - ethslurp_range_of_blocks (Failed)
        109 - ethslurp_no_record_in_block_range_long (Failed)
        110 - ethslurp_single_block_range_long (Failed)
        111 - ethslurp_range_of_blocks_long (Failed)
        117 - ethslurp_no_record_in_dates_range (Failed)
        118 - ethslurp_single_date_range (Failed)
        119 - ethslurp_date_range_1 (Failed)
        120 - ethslurp_date_range_2 (Failed)
        126 - ethslurp_no_record_in_dates_range_long (Failed)
        127 - ethslurp_single_date_range_long (Failed)
        128 - ethslurp_date_range_1_long (Failed)
        129 - ethslurp_date_range_2_long (Failed)
        130 - ethslurp_in_tx_filter (Failed)
        131 - ethslurp_out_tx_filter (Failed)
        132 - ethslurp_in_tx_filter_long (Failed)
        133 - ethslurp_out_tx_filter_long (Failed)
        134 - ethslurp_invalid_format (Failed)
        135 - ethslurp_out_txt_format (Failed)
        136 - ethslurp_out_csv_format (Failed)
        137 - ethslurp_out_html_format (Failed)
        139 - ethslurp_options_combination_2 (Failed)
        140 - ethslurp_verbose_options (Failed)
        141 - ethslurp_invalid_format_long (Failed)
        142 - ethslurp_out_txt_format_long (Failed)
        143 - ethslurp_out_csv_format_long (Failed)
        144 - ethslurp_out_html_format_long (Failed)
        146 - ethslurp_options_combination_2_long (Failed)
        147 - ethslurp_verbose_options_long (Failed)
        149 - grabABI_verbose1 (Failed)
        279 - getBlock_bloom (Failed)
        280 - getBlock_blooms (Failed)
        281 - getBlock_range (Failed)
        283 - getBlock_raw_01 (Failed)
        284 - getBlock_raw_02 (Failed)
        285 - getBlock_raw_03 (Failed)
        286 - getBlock_raw_04 (Failed)
        287 - getBlock_force_01 (Failed)
        288 - getBlock_cache_01 (Failed)
        289 - getBlock_cache_02 (Failed)
        290 - getBlock_cache_03 (Failed)
        291 - getBlock_cache_04 (Failed)
        292 - getBlock_check_01 (Failed)
        293 - getBlock_check_02 (Failed)
        294 - getBlock_check_03 (Failed)
        296 - getBlock_parity_hex (Failed)
        299 - getBlock_force_02 (Failed)
        300 - getBlock_multi1 (Failed)
        301 - getBlock_multi2 (Failed)
        303 - getBlock_terse_yes_raw (Failed)
        304 - getBlock_cmd_file1 (Failed)
        309 - getBloom_bloom (Failed)
        310 - getBloom_blooms (Failed)
        311 - getBloom_range (Failed)
        316 - getTrans_preload (Failed)
        323 - getTrans_three_ways (Failed)
        324 - getTrans_by_file (Failed)
        325 - getTrans_by_file_long_v (Failed)
        326 - getTrans_by_file_v (Failed)
        328 - getTrace_00 (Failed)
        329 - getTrace_01 (Failed)
        330 - getTrace_02 (Failed)
        331 - getTrace_03 (Failed)
        332 - getTrace_04 (Failed)
        333 - getTrace_05 (Failed)
        334 - getTrace_06 (Failed)
        335 - getTrace_07 (Failed)
        336 - getTrace_08 (Failed)
        337 - getTrace_09 (Failed)
        338 - getTrace_10 (Failed)
        339 - getTrace_11 (Failed)
        340 - getTrace_12 (Failed)
        341 - getTrace_13 (Failed)
        342 - getTrace_14 (Failed)
        343 - getTrace_15 (Failed)
        344 - getTrace_16 (Failed)
        345 - getTrace_17 (Failed)
        346 - getTrace_18 (Failed)
        347 - getTrace_19 (Failed)
        348 - getTrace_20 (Failed)
        349 - getTrace_21 (Failed)
        350 - getTrace_22 (Failed)
        351 - getTrace_23 (Failed)
        352 - getTrace_24 (Failed)
        353 - getTrace_25 (Failed)
        354 - getTrace_26 (Failed)
        355 - getTrace_27 (Failed)
        356 - getTrace_28 (Failed)
        364 - getBalance_tip_4 (Failed)
        365 - getBalance_from_file (Failed)
        368 - getBalance_e_tip_4 (Failed)
        377 - isContract_no_options_2 (Failed)
        383 - isContract_seven_addrs (Failed)
        393 - isContract_from_file (Failed)
        402 - isContract_multiple_addr_2 (Failed)
        407 - isContract_display_code_4 (Failed)
        408 - isContract_display_code_5 (Failed)
        410 - isContract_long_display_code_2 (Failed)
        435 - whenBlock_mixed_block_and_date (Failed)
        438 - whenBlock_intermediate_block_2 (Failed)
        474 - whenBlock_special_block_tangerine (Failed)
        475 - whenBlock_special_block_spurious (Failed)
        476 - whenBlock_special_block_stateclear (Failed)
        478 - whenBlock_special_block_multi1 (Failed)
        479 - whenBlock_special_block_multi2 (Failed)
        482 - whenBlock_02 (Failed)
        483 - whenBlock_03 (Failed)
        498 - cacheMan_list (Failed)
        499 - cacheMan_check (Failed)

----------------------------------------

For the differences I attach here a zip file with all the working results, just deploy them at your side (under test/working) and will be faster for you to analize what is wrong there. I tested a few ones and seems that they are just minor issues and small details, but not sure.

This .tar.gz package only contains the .txt I obtained after running "make test" at "warp" node. It only contains .txt files, so you can safely deploy it at test/working path.

cd test/working
gunzip xxxx.gz
tar xvf xxx.tar    (these steps should deploy only the .txt files I obtained today)

[parity_warp_tests_results.tar.gz](https://github.com/Great-Hill-Corporation/quickBlocks/files/1289628/parity_warp_tests_results.tar.gz)

**Comment by tjayrush** [comment]
I posted #370 because there is at least one bug here.

I also made three small changes to stop writing certain 'temporal' messages to the screen during test mode (this will fix five or six of these failed tests).

Also--if you enter an API for EtherScan before running the ethslurp tests, I think all of those tests will pass.

Finally--most of the getBlock and getBloom tests fail because they are on later blocks such as 3,500,000 or 4,000,000.  These will probably pass once you're fully synced.

Please close this one for now. I marked it as delayed (#293) and we will re-open it after 0.2.0 is released. Your node should be fully synced by then.

Note that --warp mode on parity may report that it's synced to the end of the chain >4,250,000, but in reality it isn't. It starts by syncing the latest block and then goes back and "fill in" all the blocks it skipped in the middle. It does this so it appears the node is in sync (and one can interact with it as if it were live), but then it doesn't have all the history.

Please close this one but leave it marked as delayed.

**Comment by crodnun** [comment]
Closing per Thomas request

**Comment by tjayrush** [comment]
This lead to the FALLBACK feature. I just re-read this and there's nothing here that isn't covered elsewhere.

**Comment by xtien** [comment]
How is this item closed? I got this message, db corrupted, deleted, now I'll spend three days to get the chain back in sync? Second time this happens in two weeks.

**Comment by tjayrush** [comment]
I don't think parity's corrupted database has anything to do with QuickBlocks. QuickBlocks uses Parity's RPC interface to query the data, but it doesn't do touch Parity's database in any way. Do you have adequate disc space? Have you check the parity repo for issues related to corrupted databases?
