### ISSUE TITLE
What is apt-get, brew, etc?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#378]
Are the package managers for Ubuntu / Mac? How hard are they to use?

**Comment by AFDudley** [comment]
apt-get/apt is the suite tools used by debian based linux distributions for managing packages. (https://wiki.debian.org/Apt)

Homebrew is used for managing packages in OSX, but it's a little different because it doesn't have full control over the system... it's sort of like a chroot if you're familiar with such things.
(https://brew.sh/)

Also, hello. Your project looks interesting 😄

**Comment by tjayrush** [comment]
Are they hard to use? Currently, we do a `cmake install` command, which is great, but it's not one-stop.

**Comment by AFDudley** [comment]
The short answer is they are not difficult to use.
This will get you started with ubuntu:
https://askubuntu.com/questions/71510/how-do-i-create-a-ppa

Here is how you do a similar thing for homebrew:
https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by tjayrush** [comment]
Thanks for the info. I am going to close `delay` this for now (i.e. close it, but track it in #293). I'll re-open it after release 0.2.0 which will happen in the coming weeks.
