### ISSUE TITLE
./src/libs/include folder is redundant and should be removed.

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#384]
The build does not quite work correctly in some cases. The tools/apps do not rebuild if I touch a .h file in a library. This happens because the CMakeLists.txt files for the tools/app reference `./libs/include`, but the various libraries' CMakeLists.txt reference header files directly from the library folders. 

**How to reproduce:**

    touch ./src/libs/utillib/basetypes.h
    make

Everything (both libraries and tools) should rebuild. Only the libraries and the test-libs test cases re-build. The tools and apps only link (they should build because the header changed). If I then do:

    make

nothing builds and nothing links as if everything is up-to-date, but the tools are not up to date. This becomes clear with these commands:

    cmake ../src
    make

After doing this, the tools rebuild, but the libraries do not. If I change the format of a data structure in `utillib` for example, this causes core dumps.

**To fix:**

The original reason I created ./src/libs/include was because I thought I was going to copy it to /usr/local/include (this was before we completed `make install`). To solve this I would like to remove ./src/libs/include and make the tools and apps reference all of the library folders directly just like the test-libs test cases. I think it's a one line change, but I was concerned that one line change would break `make install`.

**How I know it's fixed**

The folder ./src/libs/include is removed, and when I `touch ./src/libs/include/basetypes.h`, every test, tool and application builds.

**Comment by tjayrush** [comment]
Duplicate at #377

**Comment by crodnun** [comment]
I have done the following (everything at development branch, feel free to merge these changes into master one in the next round).

1) Removed the src/libs/include directory and its content from repository (and its content). Header files are already present at each lib path.

2) Added at root CMakeLists.txt a new variable called BASE_INCLUDE that contains a list of paths with the libs includes required everywhere.

3) Modify at src/apps/CMakeLists.txt the include_directories() statement to use the BASE_INCLUDE instead of the old src/libs/include directory no longer present at repository.

4) Modify at src/tools/CMakeLists.txt the include_directories() statement to use the BASE_INCLUDE instead of the old src/libs/include directory no longer present at repository.


Tested that everything compiles using the new BASE_INCLUDE variable and also that when you modify a header file, all the affected items are rebuilt again.

Test it again at your side and let me know if it works now as you expected.

**Comment by tjayrush** [comment]
This works. I pushed the changes to 'master.' Thanks.
