### ISSUE TITLE
What does ~/.quickBlocks folder contain?

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/quickBlocks#395]
Just show me the results of `find ~/.quickBlocks -exec ls -l '{}' ';'`

On a brand new install

    After doing `cmake ../src`
    After doing `make`
    After doing `sudo make install`
    After doing `make test`

And then the same first three steps, but with `FALLBACK=infura make test` as the fourth step.

I want to see if the files in the cache using a new install for a 'local running node' and the files in the cache when running against infura are identically sized.

You have to clear the cache in between to make sure the blocks from infura are overwritten as we only write blocks to the cache once (since they are immutable).

**Comment by crodnun** [comment]
Hi Thomas, one doubt here, when you prefer to obtain the output, now or after the latest issue we created to modify the installation?

**Comment by tjayrush** [comment]
I fixed two simple test cases that were reporting 'temporal' data. They now pass. Plus--for me--the remaining test cases were fixed when I did FALLBACK=infura and added an API key from etherscan.io. When I did those two things (and fixed the two test cases), I get 100% pass rate.

Please do this: (1) add in the etherscan.io API key, and (2) run the tests with FALLBACK=infura. If you get any failed test cases, please write a bug against those test cases.  Please provide a 'diff' of the working vs. the gold test case, so I can understand what failed, as I am seeing 100% pass from my end.

Thanks.

**Comment by crodnun** [comment]
Hi Thomas, 

I reviewed this part and I forgot to stop parity to apply fallback, here you have what I did at Ubuntu parity node:

1) using my ethscan.io key  (it is present at toml file)
2) and FALLBACK=infura, 
3) and stopping the parity process.
4) Running the cmake + make test

I obtain the following failures:

97% tests passed, 8 tests failed out of 315

The following tests FAILED:
         81 - serialize_README (Failed)
         82 - serialize_00 (Failed)
         86 - ethprice_verbose_00 (Failed)
        134 - makeClass_nonexist (Failed)
        140 - makeClass_list (Failed)
        141 - makeClass_edit (Failed)
        142 - makeClass_run (Failed)
        143 - makeClass_run_ns (Failed)

Comparing results I obtained with gold files:

-------------------------------------------------------------------------------------------------------------------
1) For test 134- makeClass_nonexist  I obtain:

  ./classDefinitions folder does not exist. Quitting...

  Usage:    makeClass [-e|-f|-l|-h|-c|-n|-s|-r|-a|-v|-h] className  
  Purpose:  Creates a C++ class based on definitions found in ./classDefinition/<className>.
             
  Where:    
        className             name of C++ class(es) to process (required)
        -e  (--edit)          edit <className(s)> definition file in local folder
        -f  (--filter val)    process only files with :filter in their names
        -l  (--list)          list all definition files found in the local folder
        -h  (--header)        write headers files only
        -c  (--source)        write source files only
        -n  (--namespace val) surround the code with a --namespace:ns
        -s  (--silent)        on error (no classDefinition file) exit silently
        -r  (--run)           run the class maker on associated <className(s)>
        -a  (--all)           clear, edit, list, or run all class definitions found in the local folder
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

--------------------------------------------------------- And it is expected -----------------------------------

 No class definition file found at ./classDefinitions/x.txt


  Usage:    makeClass [-e|-f|-l|-h|-c|-n|-s|-r|-a|-v|-h] className  
  Purpose:  Creates a C++ class based on definitions found in ./classDefinition/<className>.
             
  Where:    
        className             name of C++ class(es) to process (required)
        -e  (--edit)          edit <className(s)> definition file in local folder
        -f  (--filter val)    process only files with :filter in their names
        -l  (--list)          list all definition files found in the local folder
        -h  (--header)        write headers files only
        -c  (--source)        write source files only
        -n  (--namespace val) surround the code with a --namespace:ns
        -s  (--silent)        on error (no classDefinition file) exit silently
        -r  (--run)           run the class maker on associated <className(s)>
        -a  (--all)           clear, edit, list, or run all class definitions found in the local folder
        -v  (--verbose)       set verbose level. Either -v, --verbose or -v:n where 'n' is level
        -h  (--help)          display this help screen

  Powered by QuickBlocks

------------------------------------------------------------------------------------------------------------------

Seems that I need a hidden folder ./classDefinitions somewhere (this could explain the failures at makeClass). Do I need to add it somehow ?

------------------------------------------------------------------------------------------------------------------

For the ethprice -v seems that gold copy differs from what I obtain , maybe just delay issues, I repeated and now passes, so seems that sometimes we do not obtain whole information.
-----------------------------------------------------------------------------------------------------------------

The serialize test cases failing is because I do not have this folder at my workspace, it is missing at github and it is not able to compare both files. We should add it. Let me know if I proceed

**Comment by tjayrush** [comment]
Concerning the missing 'classDefinitions' folder, I think you have to run from the ./test/gold/apps/makaClass folder. Remember this line: https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/tools/scripts/testCheck.py#L125

**Comment by tjayrush** [comment]
EthPrice may sometimes not work if the remote site (poloniex) is down.

I added a .gitignore file in ./tests/working/libs/etherlib/serialize. It should work now.

**Comment by tjayrush** [comment]
Assuming the makeClass works from the ./test/gold/apps/makeClass folder, and the ethPrice works more consistently, and you can pass ./serialze if running from the gold test folder, you may close this.

**Comment by crodnun** [comment]
OK,

Now they pass, Closed
