### ISSUE TITLE
Improvement at getTokenBal when token or address does not exist

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#412]
It will be a nice improvement if we can detect when the user made a mistake and either the token or the account does not exist.

When I run test cases using fake values with valid format like the following, at the first example the token is just an arbitrary value, on the second both are made up values:

./getTokenBal 0xd26114cd6EE289AccF82350c8d84870000000000 0x5e44c3e467a49c9ca0296a9f130fc43304000000

./getTokenBal 0xd26114cd6EE289AccF82350c8d84870000000000 0x5e44c3e467a49c9ca0296a9f130fc43304000000

In these scenarios we report that it is a 0 balance when maybe we can warn the user that they do not exist. I do not know if this is feasible, but would help to detect when you made at typo entering an invalid digit at your address or token.

**Comment by tjayrush** [comment]
It isn't feasible to detect a bad address since every address with 0x and 40 characters (as long as they are 40 hex characters) is a valid address. I can check to see if the address is a smart contract, but I cannot test to see if the address implements the ERC20 token standard (people are working on this, but it's not available currently).

I will think about this though. It's a good issue to raise. I might be able to come up with something that doesn't slow things down in the general case, but does provide some warning of some type (although it will never be fool proof).

**Comment by tjayrush** [comment]
I am going to delay this one because I don't want to check if an address is a contract each time this is used (it's pretty much slower).

I delayed it, and will keep track of it in #293. Please close this.

**Comment by crodnun** [comment]
OK closing per Thomas request.

**Comment by tjayrush** [comment]
Nice idea, but not feasable. Closting.
