### ISSUE TITLE
getBalance README.md improvements and feedback

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#422]
Here you have my feedback and suggestions for this tool help. I tried to write them from the point of view of a newcomer so feel free to pick those that are more important for you, my goal for me is to make this project user-friendly and easy to use for everybody. The first contact with the documentation is line separating success/failure :-).

1) We should indicate that block-s parameter is optional and when not supplied we return the balance at latest block available. Block is not always required (indeed is optional). We try to say this but for a user that is not used to the tool could be confusing, let's indicate clearly that in absence of blocks, we use latest available.

2) We should indicate also that every option can be provided in two ways: short/long formats. This is something that we should review everywhere in the project. A new user, needs to identify clearly that we support simply 2 formats, if you look at the table where we describer the commands, it is not clear for a newcomer what does the column "Full Command" means.  A quick explanation at the beginning saying this would be welcome, this way is up to you which format you want to use when passing an option.

3) We indicate that this command usage is as follows:

    getBalance [-l|-n|-d|-v|-h] <address> [address...] [block...]

but when we describe the syntax we say:

    address_list   is ......
    block_list       is .....

we should be consistent and use the same terms at both sides, if we use address_list, at usage we should use address_list (this way user can match usage and description easier). The same applies to block_list.

Maybe just using at usage this (could be clearer)

    getBalance [-l|-n|-d|-v|-h] address_list [block_list]   

The same happens at Notes:  here we use "addresses" a different term, my advice is to be consistent again and always use the same terms everywhere. This way the user does not get confused.

4) The option -l/--list requires an input file, maybe it would be clearer if we modify the usage to this:

    getBalance [-l fn|-n|-d|-v|-h] address_list [block_list]    ---- Notice that I put here the fn inside the option

5) We should link this line 

    this tool retrieves information from the local node or the ${FALLBACK} node, if configured

with another README.md somewhere to indicate what is the FALLBACK mechanism, how it is configured at environment and what are the supported values.

6) It is not clear for me what the [start-end) at blocks_lists mean, as a user, I have tested many combinations and they did not work. How this feature is used? Clearly if I could not understand it, this part should be reviewed.

7) The verbose option needs to specify the supported log levels, as a final user if I want to debug something would like to know what are the supported values there.

8) Being picky, at list option, both formats should receive the fn parameter:

    -l  fn   | --list fn        (The first column seems that does not require it)

**Comment by tjayrush** [comment]
> ...I tried to write them from the point of view of a newcomer....

Let's focus on the 'well-familiar with blockchain' new comer. In other words, our user knows pretty much about the space already...

> We should indicate that "block' parameter is optional and when not supplied we return the balance at latest block available.

Done...

> We should indicate also that every option can be provided in two ways: short/long formats.

I think that is clear when I do this:

    -l (--list...)

I think the type of users we will get will understand this easily.

One thing to keep in mind--by version 1.0, we might be using rust. Rust has built in options parsing / help display packages and as part of the port to Rust, many thing will be improved / made more professional.

> it is not clear for a newcomer what does the column "Full Command" means

I changed it to "Short Cut" and "Option". Again, our semi-sophisticated user should get this, I think.

> 
> We indicate that this command usage is as follows:
>        getBalance [-l|-n|-d|-v|-h] [address...] [block...]
> but when we describe the syntax we say:
>        address_list   is ......
>        block_list       is .....
> we should be consistent and use the same terms at both sides....

I like the way it looks both visually and informationally. I like the <address> [address...] and, while I do agree that it might be better if they both said address_list, it would not look as good in the one case, and mess up the formatting in the other. It's a compromise in my mind. I think it's okay, so for this tool (and all others) it will be okay for it to say <address> [address..] in one place and 'address_list' in another. The user will understand. Thank you so much for the suggestion though.

> The option -l/--list requires an input file, maybe it would be clearer if we modify the usage to this:
> 
>     getBalance [-l fn|-n|-d|-v|-h] address_list [block_list]
>

I fixed this in the usage section (as mentioned above) but not in the option detail section because it would mess up the visual formatting (at least to my eye). I'm pretty sure the user understands. If we get bug reports against it, we can revisit the issue.

> We should link this line
> this tool retrieves information from the local node or the ${FALLBACK} node, if configured

I added a small text that says "see the documentation" (even though we have no documentation--but we're still only 0.2.0, so it's okay).

> with another README.md somewhere to indicate what is the FALLBACK mechanism, how it is configured at environment and what are the supported values.

This is going to be missing in version 0.2.0. It's on my list of things to do when I finally get around to writing the real documentation.

> 
> It is not clear for me what the [start-end) at blocks_lists mean, as a user, I have tested many combinations and they did not work. How this feature is used? Clearly if I could not understand it, this part should be reviewed.

This was messed up. It only meant you had to specify a start and end block with a dash between them (no spaces). It meant inclusive of the first block, exclusive of the end block, but I removed the bracketing. If it's still not clear, please specify specific wording changes and I'll fix it.

> 
> The verbose option needs to specify the supported log levels, as a final user if I want to debug something would like to know what are the supported values there.

This will have to wait. It is wrong in all the tools, but I won't fix it for this release. As I get more into each tool, I will identify different debugging levels and then this will make sense. I think the user will understand since we're only at 0.2.0

> 
> Being picky, at list option, both formats should receive the fn parameter:
> 
> -l fn | --list fn (The first column seems that does not require it)

I understand this, but I disagree because I want it to be visually consistent. In other words, the way it looks is as important to me as what it says.

**Comment by tjayrush** [comment]
I tried to comment on each item above. Do me a favor with this one. If there are any remaining issues (I lost track to be honest), please close this issue and write specific issues for each remaining open item. Also--when you make an issue, if you add very specific instructions for me ("change the words XYZ to the words ABC") that would make it easier for me. These wording issues are little bit stylistic, so six of one / half a dozen of another. If you give me specific instructions, I can just make the change without thinking about it too much.

**Comment by crodnun** [comment]
OK, I could not see these changes pushed to develop branch. Will review them when ready.

**Comment by tjayrush** [comment]
It should be up now.

**Comment by crodnun** [comment]
OK closing
