### ISSUE TITLE
getTokenBal README.md improvements and feedback

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#427]
The same I reported you for getBalance applies here:

1) Suggestion for new help message:

getTokenBal [-b|-l fn|-n|-d|-v|-h] <address_list> [block_list]

This way you show that:

address_list is mandatory and can have 1 or more items, first always token addr
block_list is optional

Notice also that I added the fn required by -l option.

2) Fields along the README.md should be consistent. We should use the same term to refer to address_list everywhere, at help, at table and at Notes.

Instead of repeating everything I think that we should create a single issue for every tool, we need to detail FALLBACK usage.

Feel free to join this issue with the #422

**Comment by tjayrush** [comment]
I added the 'fn' to the -l option in the usage. I don't want to add it to the -l part of the detail options list because it will mess with formatting (it will make it either un-even or too wide), so I think that's okay.

Concerning address_list vs. <address> [address...] I like it the way it is, so you don't need to report that one any longer. Thanks.

I think this one can be closed if you're satisfied.

**Comment by crodnun** [comment]
I do not see these changes pushed yet, let me know when they are available to close this issue.

**Comment by tjayrush** [comment]
It should be up now.

**Comment by crodnun** [comment]
I could not see these changes, but closing anyways

**Comment by tjayrush** [comment]
Are you on master or develop?
