### ISSUE TITLE
getBloom supports the hidden option --source and -s

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#454]
Looking at the test cases defined so far, I see that we support these options:

--source:cache
-s:node
--parity

These options are not documented at README.md. Do we keep them hidden for the moment?

**Comment by tjayrush** [comment]
I'm going to ask you to close it (I marked it as 'delayed' and added it to #293.)

Just to document what this is:
- `--source:node` is equivalent to `--raw`.
- `--source:cache` forces QuickBlocks to pull the data from the cache or fail
- `--source:infura` forces it to fallback to infura
- `-s` is a shortcut for `--source:...`
- normal operation is
   - look in cache, if not found...
   - look for a local node, if not found...
   - look for ${FALLBACK}, if not found
   - fail

For the time being (release 0.2.0) these options should remain hidden since it's not fully ready yet. I think it's fine to leave them in the test cases just so we know they don't get broken by some other change.

The `--parity` options is similar in the sense that it's available to every tool, but not documented because it's not really ready just yet. Again, I think it's okay to leave it in the test cases so it doesn't get accidentally broken, but we won't expose it for version 0.2.0.

**Comment by crodnun** [comment]
OK closing per Thomas request. This part is delayed to next releases

**Comment by tjayrush** [comment]
Referenced from list of hidden commands issue.
