### ISSUE TITLE
Doubt using getTrans

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#463]
When I run the following command:

./getTrans --raw 0x0766ec95bf12f9600afc6c33c287f9d2356d85f15f0d7eeeb6647f5d4ddfbce1

I obtain the following output:

getTrans argc: 3 [1:--raw] [2:0x0766ec95bf12f9600afc6c33c287f9d2356d85f15f0d7eeeb6647f5d4ddfbce1] 
getTrans --raw 0x0766ec95bf12f9600afc6c33c287f9d2356d85f15f0d7eeeb6647f5d4ddfbce1 
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid length 1, expected a 0x-prefixed, padded, hex-encoded hash with length 64."},"id":4}

Seems that we receive an error saying, invalid length "1". I do not understand this behaviour, so I open a doubt for the same, because I am not sure if it is a bug or not.

If it is a bug, please go ahead and update the labels, if not just kindly tell me what is happening here and I will close the same.

I expected here a kind of validation to reject the hash if it is invalid, but I obtain the error detailed above.

**Comment by tjayrush** [comment]
Did you purposefully manufacture this as an invalid transaction hash?  In other words, did you change a number or something?  

The request is asking for the "raw" json code that the node returns, so in a sense this is exactly what the user asked for. The only check QuickBlocks does on the hash is its length and that it started with '0x' and contains only 0-9a-f.  Since it does that, it simply returns the node's response.

The trouble comes when we do:

    getTrans 0x0766ec95bf12f9600afc6c33c287f9d2356d85f15f0d7eeeb6647f5d4ddfbce1

or 

    getTrans -v 0x0766ec95bf12f9600afc6c33c287f9d2356d85f15f0d7eeeb6647f5d4ddfbce1

both of which appear to return an empty transaction. I've been thinking I need an "error" transaction (or block, or trace, or receipt) that returns an obviously incorrect data structure.

Let's delay this one. I need to fix this, but it's a bigger change than I want to do right now given that I want to release. Please close it and mark it delayed. I've added it to the 'delayed' list in #293.

**Comment by crodnun** [comment]
Delayed and closing per Thomas request

**Comment by tjayrush** [comment]
This is now fixed.
