### ISSUE TITLE
Binary Blocks Cache Directory Structure Needs to Be Specified for Correct Execution

### ISSUE THREAD

**Issue by agericke** [Great-Hill-Corporation/quickBlocks#616]
When trying to retrieve binary blocks from cache, if they have not been stored strictly following the structure specified in the White Papers (blocks stored in folders of 1,000 blocks, block's 3957000 path would be /cache/blocks/00/39/57/003957000.bin), quickblocks application does not finds the blocks in cache and queries it to the node although having them in cache.

The block structure is mentioned as a recommendation but not as an obligation.

When running **getBlock()**, it triggers **geBinaryFilename()**, which triggers **getFIlename_local()**, which looks for the block binary file following the structure of folders specified above. If you do not stored them that way, the binary file won't be find, and as a result **getBlock()** will set **curlContext.provider** to **local** and will query the block to the running Ethereum node, resulting in a very slow procedure if compared when retrieving binary cached files.

In addition, during initialization blockCachePath is set to **~/.quickBlocks/cache/**, but if blocks are stored directly to cache directory following directory structure (i.e. **~/.quickBlocks/cache/00/00/39/57/003957000.bin** for block 3957000), instead of storing them under **~/.quickBlocks/cache/blocks/...**, same problem happens as function **getBinaryFilename()** replaces _"/00/"_ to _"blocks/00"_.

Then I believe it would be helpful to specify the structure to store blocks in a Readme instead of the White Paper as someone may not realise this, and the increment in speed that provides quickBlocks will not be noticed.

**Comment by tjayrush** [comment]
Thanks again for another excellent issue.

1) I don't really like the way q-blocks chooses to store the data in ~/.quickBlocks/cache because that may not be the place where the user wants the data to be stored. Plus, if that is not an SSD drive, it may make the cache slower,

2) I think the cache does have to be in $CACHE/blocks. Other apps in the QuickBlocks world also store their data in the cache, so I want to keep things separated. For example, the blooms are stored in $CACHE/blooms and some other stuff is also stored under $CACHE.

3) I've debated forcing the user to select the location of the $CACHE, but in any case I agree, it should be in the README file / install instructions.

**Comment by tjayrush** [comment]
Reorganizing all issues, therefore closing this one.

**Comment by tjayrush** [comment]
It is required of the user not to store the binary cache in a custom location and if they do, they can modify the code accordingly.
